name: Generate SRS

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install maxminddb
    - name: Download Merged-IP sing-box
      run: |
        curl -LO https://github.com/NetworkCats/Merged-IP-Data/releases/latest/download/Merged-IP.mmdb
        sha256sum ./Merged-IP.mmdb
        curl -LO https://github.com/SagerNet/sing-box/releases/download/v1.13.3/sing-box-1.13.3-linux-amd64.tar.gz
        tar xvf sing-box-1.13.3-linux-amd64.tar.gz
        mv sing-box-1.13.3-linux-amd64/sing-box ./
        rm -rf sing-box-1.13.3-linux-amd64
        rm -rf *.tar.gz
    - name: Generate rule-set source
      run: |
        rm -rf ruleJson
        rm -rf ruleSrs
        mkdir ruleJson
        mkdir ruleSrs
        python ./generate_rule_set.py
    - name: Compile to srs
      run: |
        for file in ./ruleJson/*.json; do
          ./sing-box rule-set compile "$file"
        done
        mv ./ruleJson/*.srs ./ruleSrs/
    - name: Commit Push
      run: |
        git config user.name "action-bot"
        git config user.email "action-bot@github.com"
        if [ -n "$(git status --porcelain)" ]; then
          git add .
          git commit -m "update rule"
          git push
        fi
